# Use the Python image as the base image
FROM python:3.11.4

RUN mkdir -p /home/app
COPY . /home/app
# Set the working directory within the container
WORKDIR /home/app

#openai dependency
RUN pip install openai==0.27.8


# the command to run the python app
CMD ["python", "project1.py"]