# Use the official Python image as the base image
FROM python:3.11.4

RUN mkdir -p /home/app
COPY . /home/app
# Set the working directory within the container
WORKDIR /home/app

RUN pip install openai==0.27.8


# Copy the entire current directory into the container
#COPY app.py .
# Expose the port that your Flask app will run on


# Define the command to run your Flask app
CMD ["python", "project1.py"]